env: play

initial-cluster-setup:
  google-oauth:
    GoogleEnabled: # [true | false]
    GoogleClientSecret: 
    GoogleClientId: 
    GoogleRestrictedDomain: 

  github-oauth:
    GitEnabled: # [true | false]
    GitClientSecret: 
    GitClientId: 
    GitRestrOrgs: 
    
  htpasswd:
    HtpasswdEnabled: # [true | false]
    HtpasswdData: 

  ldap-oauth:
    LdapEnabled: true # [true | false]
    LdapBindPassword: Gepaplexx2022!
    LdapBindDn: "CN=GP Admin,OU=Users,OU=GEPAPLEXX,DC=gp,DC=local"
    LdapUrl: ldap://10.20.26.10:389/OU=Users,OU=GEPAPLEXX,DC=gp,DC=local?cn?sub
    LdapUsersQuery: "OU=Users,OU=GEPAPLEXX,DC=gp,DC=local"

  cluster-config:
    ArgocdWorkflowrepositoryUsername: 
    ArgocdWorkflowrepositorySshPrivateKeyBase64:
    AlertsSlackUrl:
  
  cluster-issuer:
    SolversAccesKeyId:
    SolversSecretAccessKey:

  console-patches:
    RouteNameOverride: # [true | false]

cluster-setup-checkpoint:
  rook-ceph-instance:
    RookCephInstanceEnabled: # [true | false]
    SlackChannel: # [Slack Url for Alerts ]

  keycloak-instance:
    KeycloakDbPassword:  # Database password for Keycloak Postgresql Database
    KeycloakOcpClientSecret:  # ClientSecret for OauthClient "keycloak" in OpenShift. If left empty, will be autogenerated

cluster-applications:
  cluster-updater:
    SlackChannel: 

  cluster-logging:
    ClusterLoggingEnabled: # [true | false]
    ClusterLoggingRequestMemory: 
    ClusterLoggingLimitsMemory: 
  
  cluster-monitoring:
    InfranodesEnabled: # [true | false]
    SlackChannelCritical: # See Incoming Webhooks for apps in https://api.slack.com/apps
    SlackChannelMonitoringInternalApplications: # See Incoming Webhooks for apps in https://api.slack.com/apps
    # Path to alertmanager config file, empty => use default
    AlertmanagerConfig: 

  gepaplexx-cicd-tools:
    PostgresqlPassword: ""
    PostgresqlPostgresPassword: ""
    PostgresqlUsername: ""
    ArgoWorkflowsMetricsEnabled: true # [true | false]
    ArgoWorkflowsServiceMonitorEnabled: false # [true | false]
    ArgoWorkflowsClusterScopedGroupEnabled: true # [true | false]
    ArgoWorkflowsSsoIssuer: "https://sso.apps.${ENV}.gepaplexx.com/realms/${REALM}" # Beispiel, nicht vergessen zu ersetzen!
    ArgoWorkflowsSsoClientSecret: ""
    ArgoWorkflowsMinioSecretkey: ""

  vault:
    AutoUnsealCreds:
