env: 

initial-cluster-setup:
  google-oauth:
    GoogleEnabled: # [true | false]
    GoogleClientSecret: 
    GoogleClientId: 
    GoogleRestrictedDomain: 

  github-oauth:
    GitEnabled: # [true | false]
    GitClientSecret: 
    GitClientId: 
    GitRestrOrgs: 
    
  htpasswd:
    HtpasswdEnabled: # [true | false]
    HtpasswdData: 
  
  cluster-config:
    ArgocdWorkflowrepositoryUsername: 
    ArgocdWorkflowrepositorySshPrivateKeyBase64:
    AlertsSlackUrl:
  
  cluster-issuer:
    SolversAccesKeyId:
    SolversSecretAccessKey:

  console-patches:
    RouteNameOverride: # [true | false]

cluster-setup-checkpoint:
  rook-ceph-instance:
    RookCephInstanceEnabled: # [true | false]
    SlackChannel: # [Slack Url for Alerts ]

cluster-applications:
  cluster-updater:
    SlackChannel: 

  cluster-logging:
    ClusterLoggingEnabled: # [true | false]
    ClusterLoggingRequestMemory: 
    ClusterLoggingLimitsMemory: 
  
  cluster-monitoring:
    InfranodesEnabled: # [true | false]
    SlackChannel: 
    # Path to alertmanager config file, empty => use default
    AlertmanagerConfig: 

  gepaplexx-cicd-tools:
    PostgresqlPassword:
    PostgresqlPostgresPassword:
    PostgresqlUsername:
    ArgoWorkflowsMetricsEnabled: # [true | false]
    ArgoWorkflowsServiceMonitorEnabled: # [true | false]
    ArgoRolloutsMetricsEnabled: # [true | false]
    ArgoRolloutsServiceMonitorEnabled: # [true | false]

  vault:
    AutoUnsealCreds:
    MetricsUsername:
    MetricsPassword:
