env: "play" # zBsp.: play

argo-bootstrap:
  cluster-applications:
    Name: "cluster-applications"
    # Namespace: "gepardec-run-gitops" # Optional
    # TargetNs: "gepardec-run-gitops" # Optional
    # ArgoProject: "bootstrap-argoproject" # Optional
    ValuesFile: "values/values-vshn.yaml"
    Path: "cluster-applications/gp-cluster-applications"
    # Repo: "https://github.com/gepaplexx/gepardec-run-cluster-configuration/" # Optional
    # Revision: "main" # Optional

  initial-cluster-setup:
    Name: "initial-cluster-setup"
    ValuesFile: "values/values-vshn.yaml"
    Path: "initial-cluster-setup/gp-initial-cluster-setup"
    # Namespace: "" # Optional
    # TargetNs: "" # Optional
    # ArgoProject: "" # Optional
    # Repo: "" # Optional
    # Revision: "" # Optional

initial-cluster-setup:
  keycloak-operator:
    KeycloakOperatorChartVersion: "*" 

  external-secrets:
    ExternalSecretsChartVersion: "*" 

  grafana-operator:
    GrafanaOperatorChartVersion: "*" 

  vault:
    VaultChartVersion: "*" 

  kyverno:
    KyvernoChartVersion: "*" 

cluster-applications:
  keycloak-instance:
    KeyCloakInstanceChartVersion: "*" 
    KeycloakInstanceConfigCliEnabled: true # [true | false]

  external-secrets-config:
    ExternalSecretsConfigChartVersion: "*" 

  cicd-tools:
    CicdToolsChartVersion: "*" 
    ArgoWorkflowsClusterScopedGroupEnabled: true # [true | false]

  cicd-eventbus:
    CicdEventbusChartVersion: "*" 

  gerpardec-run-cicd:
    GepardecRunCicdChartVersion: "main"

  grafana-instance:
    GrafanaInstanceChartVersion: "*" 

  grafana-dashboards:
    GrafanaDashboardsChartVersion: "main"

  multena:
    MultenaChartVersion: "*" 

  altermanager:
    AlertmanagerChartVersion: "*" 

  private-bin:
    PrivateBinChartVersion: "0.1.*"
    
vault-setup-script:
  ArgoCdWFRepoUser: ""
  ArgoCdWFRepoSSHPrivateKey: ""
  KeycloakDBPassword: ""
  KeycloakClientSecretGrafana: ""
  KeycloakClientSecretArgoWf: ""
  KeycloakProviderSecretOCP: ""
  AlertmanagerConfig: ""

initial-setup-script:
  KeycloakClientSecret: ""
  Namespace: "gepardec-run-gitops"