name: Release Containerimage

on:
  schedule:
    - cron: "0 7 * * 1"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-day-X-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout
      - name: source-version
        id: source-version
        run: |
          echo "::set-output name=version::$(cat version)"
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: push-container-image
        with:
          image: day-x-generator
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.PAT }}
          dockerfile: Containerfile
          directory: .
          addLatest: true
          tags: ${{ steps.source-version.outputs.version }},latest